name: End-to-end tests
on: [push]
jobs:
  cypress-vue:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        adapter: ['vue']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
        run: npm install -g yarn

      - name: Prepare Inertia
        run: |
          yarn install
          yarn build
          yarn cache dir

      - name: Local-link Inertia core
        run: cd packages/inertia && yarn link

      - name: Local-link @inertiajs/inertia-${{ matrix.adapter }})
        run: cd packages/inertia-${{ matrix.adapter }} && yarn link

      - name: Install Cypress Dependencies
        run: |
          cd packages/inertia-${{ matrix.adapter }}
          yarn
          yarn link "@inertiajs/inertia"
          yarn link "@inertiajs/inertia-${{ matrix.adapter }}"

      - name: Run Cypress (inertia-${{ matrix.adapter }})
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/inertia-${{matrix.adapter}}/tests
          build: yarn build
          start: yarn test:server
          wait-on: 'http://localhost:13714'
          config-file: cypress.json

