name: End-to-end tests
on: [push]
jobs:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        adapter: ['vue']
        browser: ['chrome', 'edge', 'firefox']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.3

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('yarn.lock') }}
          path: |
            ~/.cache
            **/node_modules

      - name: Build Inertia
        run: |
          yarn install
          yarn build

      - name: Local-link @inertiajs/inertia
        run: cd packages/inertia && yarn link

      - name: Local-link @inertiajs/inertia-${{ matrix.adapter }}
        run: cd packages/inertia-${{ matrix.adapter }} && yarn link

      - name: Install Cypress Dependencies
        run: |
          cd packages/inertia-${{ matrix.adapter }}/tests
          yarn
          yarn link "@inertiajs/inertia"
          yarn link "@inertiajs/inertia-${{ matrix.adapter }}"

      - name: Run Cypress (${{ matrix.browser }} / inertia-${{ matrix.adapter }})
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/inertia-${{ matrix.adapter }}/tests
          browser: ${{ matrix.browser }}
          install: false
          build: yarn build
          start: yarn run-server
          wait-on: 'http://localhost:13714'
          config-file: cypress.json

